site_name: Metsäkoetietojärjestelmän QField PoC 
copyright: 'Tekijä: <a href="info@gispo.fi">Gispo Suomi Oy</a>'
nav:
  - Alku: index.md
  - Koti: 0_index.md
  - 1. Alkuvalmistelut: 1_alkuvalmistelut.md
  - 2. Projektin vienti QFieldiin: 2_vienti.md
  - 3. QFieldin käyttö: 3_qfield.md
  - 4. QFieldistä QGISiin: 4_qfieldista_qgissiin.md
use_directory_urls: false
theme: 
  name: readthedocs
